version: '3.8'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: ecommerce_dwh
      POSTGRES_USER: dwh_user
      POSTGRES_PASSWORD: cls
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dwh_user -d ecommerce_dwh"]
      interval: 10s
      timeout: 5s
      retries: 5

  etl:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    environment:
      - DB_HOST=postgres
      - DB_NAME=ecommerce_dwh
      - DB_USER=dwh_user
      - DB_PASSWORD=cls

volumes:
  postgres_data: