version: 2

models:
  - name: dim_customers
    description: Customer dimension table
    columns:
      - name: customer_key
        description: Surrogate key
        tests:
          - unique
          - not_null

  - name: fact_orders
    description: Order fact table
    columns:
      - name: order_key
        tests:
          - unique
          - not_null